#+TITLE: dff -- duplicate file finder.

[[https://travis-ci.org/sureshsundriyal/dff.svg?branch=master]]

=dff= is a tool for locating duplicate files in a directory. The tool is
modelled after [[http://duff.dreda.org/][Duff]] without any advanced options.

* Building

#+BEGIN_EXAMPLE
cargo build --release
#+END_EXAMPLE

* Installing

#+BEGIN_EXAMPLE
cargo install
#+END_EXAMPLE

* Usage

In any mode of operation, =dff= will:

  + Recursively search through the specified directories
  + Symlinks are ignored

** Normal Mode

#+BEGIN_EXAMPLE
dff <dir1> [dir2 [dir3...]]
#+END_EXAMPLE

In normal mode of operation; =dff= searches through the specified directories
searching for duplicates using the following algorithm:

  + Only compare files if they're of equal size.
  + Compare the hashes of the beginning 1024 bytes to check whether
    they are equal.

The two checks above quickly pin-point files which might be equal.

** Thorough Mode

#+BEGIN_EXAMPLE
diff --thorough <dir1> [dir2 [dir3...]]
#+END_EXAMPLE

In =thorough= mode, instead of comparing the hash of first 1024 bytes; hash of
the complete file contents are compared. This greatly reduces the probability
of false positives.

* ToDo

  + [ ] Implement an exhaustive mode which compares the actual file
    contents instead of hashes
  + [ ] Allow json output in order to facilitate programatically
    parsing the output.
